projects:
  airbnb:
    schemaPath: Users/xuchunlei/Projects/React-Native/Airbnb/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /Users/xuchunlei/Projects/React-Native/Airbnb/graphql
